ccflags-y += -I$(src)/../../pci/intel/ipu7/

obj-m 		+= max9x.o
max9x-y += serdes.o max9296.o max96724.o max9295.o max96717.o
#obj-m		+= serdes.o
#obj-m		+= max9295.o
#obj-m		+= max9296.o
#obj-m		+= max96717.o
#obj-m		+= max96724.o
